import type { ReactNode } from 'react';

type Language = 'en' | 'zh';

function t(language: Language, english: string, chinese: string): string { return language === 'zh' ? chinese : english; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="wiki-section"><h2>{title}</h2>{children}</section>; }
function Term({ title, children }: { title: string; children: ReactNode }) { return <article className="wiki-term"><h3>{title}</h3>{children}</article>; }
function Source({ href, children }: { href: string; children: ReactNode }) { return <a href={href} target="_blank" rel="noreferrer">{children} ↗</a>; }

export function WikiPage({ language, setLanguage, onBack }: { language: Language; setLanguage: (language: Language) => void; onBack: () => void }) {
  const zh = language === 'zh';
  return <main className="wiki-page">
    <header className="wiki-topbar"><button className="wiki-back" onClick={onBack}>← {t(language, 'Back to exchange', '返回交易所')}</button><div className="wiki-brand"><span role="img" aria-label={t(language, 'Market chart', '行情图表')}>📈</span><b>FinPub Wiki</b></div><select aria-label={t(language, 'Language', '语言')} value={language} onChange={(event) => setLanguage(event.target.value as Language)}><option value="en">English</option><option value="zh">中文</option></select></header>
    <div className="wiki-hero"><span>{t(language, 'FINPUB KNOWLEDGE BASE', 'FINPUB 知识库')}</span><h1>{t(language, 'How markets work — and where this simulation deliberately differs.', '理解市场如何运作，也理解这个模拟器刻意简化了什么。')}</h1><p>{t(language, 'A bilingual guide to order books, trading participants, market microstructure, and the difference between this game, A-share trading, and U.S. listed equities.', '这是一个双语科普页：解释订单簿、交易参与者、市场微观结构，并区分本游戏、A 股和美国上市股票市场。')}</p><p className="wiki-disclaimer">{t(language, 'Education only. FinPub is a fictional simulation, not a live market, brokerage, investment recommendation, or a complete statement of exchange rules.', '仅供学习。FinPub 是虚构的市场模拟器，不是实时市场、券商服务、投资建议，也不是交易所规则的完整表述。')}</p></div>
    <article className="wiki-content">
      <Section title={t(language, 'Price is an agreement, not a verdict', '价格是成交协议，而不是唯一真相')}>
        <p>{t(language, 'A traded price is the price at which one buyer and one seller agreed to exchange. It is not automatically the correct value of an asset. A market can simultaneously have a last traded price, best bid, best ask, a fair-value estimate, and many investors’ private estimates. FinPub intentionally keeps them separate.', '一笔成交价是某个买方与某个卖方真实同意交换的价格，它不自动等于资产正确的价值。同一时刻可以同时存在最新成交价、最优买价、最优卖价、参考公允价值和不同投资者的私人估值。FinPub 有意将它们分开。')}</p>
        <p>{t(language, 'Liquidity matters because a price is not very useful when only a tiny quantity can transact there. More available orders near the current price generally make execution easier. Thin books make market-order results uncertain and can move through several price levels quickly.', '流动性很重要：如果一个价格只能成交极少数量，它的实际意义有限。现价附近可成交订单越多，执行通常越容易。订单簿很薄时，市价单的结果更不确定，也可能迅速穿透多个价格档位。')}</p>
      </Section>
      <Section title={t(language, 'Core financial language', '核心金融术语')}>
        <Term title={t(language, 'Order book, bid, ask, and spread', '订单簿、买价、卖价与价差')}><p>{t(language, 'The order book is the queue of resting orders. A bid is a buyer’s offered price; an ask is a seller’s requested price. The best bid is the highest visible buying price and the best ask is the lowest visible selling price. Their difference is the spread. A smaller spread can mean lower immediate trading cost, but does not guarantee deep liquidity.', '订单簿是等待成交的挂单队列。买价是买方愿意支付的价格；卖价是卖方要求的价格。最优买价是当前可见最高买价，最优卖价是当前可见最低卖价；两者之差是价差。更小的价差可能意味着更低的即时交易成本，但不保证市场深度足够。')}</p></Term>
        <Term title={t(language, 'Limit order and market order', '限价单与市价单')}><p>{t(language, 'A limit order controls price: a buy limit will not pay above its limit, and a sell limit will not accept below its limit. It may wait or never fill. A market order prioritizes immediacy and consumes opposing liquidity; its average execution price can differ from the last price. In FinPub, any market-order remainder cancels at the end of the auction tick.', '限价单优先控制价格：买入限价单不会高于指定价格成交，卖出限价单不会低于指定价格成交；它可能等待，也可能永远不能成交。市价单优先追求立即成交，会吃掉现有对手盘，最终平均成交价可能不同于最新价。在 FinPub 中，市价单未成交余量会在该撮合轮结束时撤销。')}</p></Term>
        <Term title={t(language, 'Maker, taker, and price/time priority', '挂单方、吃单方与价格/时间优先')}><p>{t(language, 'The maker supplies liquidity by resting in the book. The taker removes liquidity by crossing an existing quote. Many electronic venues order matching by better price first and then earlier time at the same price. FinPub uses this common teaching model: an incoming order meets a resting order and the resting limit price becomes the trade price.', '挂单方通过留在订单簿中提供流动性；吃单方通过主动跨越现有报价消耗流动性。许多电子交易场所采用先价格、后同价时间的撮合顺序。FinPub 使用这一常见教学模型：新订单与簿中静态订单成交，成交价使用静态订单的限价。')}</p></Term>
        <Term title={t(language, 'Fair value, P&L, and portfolio weight', '公允价值、盈亏与组合权重')}><p>{t(language, 'Fair value is an estimate for analysis, not a guaranteed executable price. Realized P&L comes from reducing or closing a position; unrealized P&L remains inside an open position. Portfolio weight is a marked asset value divided by total assets. FinPub includes cash as a weight, so displayed weights normally total 100%.', '公允价值是用于分析的估计，不是保证能够成交的价格。已实现盈亏来自减仓或平仓；未实现盈亏仍包含在未平仓持仓中。组合权重是标的盯市价值除以总资产。FinPub 也将现金作为权重，因此展示权重通常合计为 100%。')}</p></Term>
        <Term title={t(language, 'Volatility, news, and price impact', '波动率、新闻与价格冲击')}><p>{t(language, 'Volatility describes the size of price changes, not their direction. News changes beliefs and incentives; it does not mechanically dictate a trade. Price impact is the movement associated with executing against limited liquidity. In real markets, observed impact mixes information, urgency, hidden liquidity, other traders’ reactions, and changing conditions.', '波动率描述价格变化的幅度，而不代表价格一定上涨或下跌。新闻会改变预期与交易动机，却不会机械地规定某一笔成交。价格冲击是订单在有限流动性中执行时带来的价格移动。现实中观察到的冲击混合了信息、紧迫程度、隐藏流动性、其他交易者反应和不断变化的环境。')}</p></Term>
      </Section>
      <Section title={t(language, 'How FinPub works', 'FinPub 的市场如何运作')}>
        <p>{t(language, 'FinPub advances in discrete one-second auction ticks. It first processes requested cancellations and removes stale NPC liquidity. A scheduled event can change valuation inputs. A seeded set of NPC decisions creates orders. Pending orders are then handled in submission order, matched with price/time priority, and the game records book, participant, portfolio, and event history.', 'FinPub 以离散的一秒撮合轮推进。每轮先处理撤单请求并清理过期 NPC 流动性；预定事件会改变估值输入；随后由固定随机种子决定一批 NPC 决策并生成订单。待处理订单按提交顺序进入价格/时间优先撮合，游戏记录订单簿、参与者、组合与事件历史。')}</p>
        <p>{t(language, 'The screen displays five aggregated levels per side, while deeper orders remain in the engine. Player limit orders must select a visible level. This makes price selection understandable, but is an intentional teaching constraint rather than a universal exchange-interface rule.', '页面每边展示五个聚合价格档位，而引擎内部保留更深订单。玩家限价单必须选择可见档位。这使价格选择更直观，但它是有意的教学约束，并非所有真实交易所界面的通用规则。')}</p>
        <p>{t(language, 'The random seed determines NPC profiles, event timing, event magnitude, and random choices. Identical starting configuration, seed, starting timestamp, strategy code, strategy mode, and actions from tick zero are designed to reproduce the same sequence. Changing a manual action or code mid-run produces a different path.', '随机种子决定 NPC 档案、事件时点、事件强度与随机决策。在初始配置、种子、模拟起点、策略代码、策略模式及从第 0 轮起的操作均相同的前提下，模拟被设计为复现同一序列。中途改变手动操作或策略代码，都会产生不同路径。')}</p>
      </Section>
      <Section title={t(language, 'What this game assumes — and what reality does differently', '游戏采用的假设，以及现实市场有什么不同')}>
        <p>{t(language, 'FinPub deliberately omits brokers, clearing members, custody, securities lending, margin loans, short-sale locate processes, corporate actions, halts, hidden orders, odd lots, taxes, surveillance, exchange membership, smart order routing, and competing venues. NPCs have virtual unlimited quoting capacity to keep the lesson liquid. Real firms face capital, inventory, regulatory, risk, and operational constraints.', 'FinPub 有意省略券商、清算会员、托管、证券借贷、融资融券、卖空借券定位、公司行为、停牌、隐藏订单、零股、税务、市场监察、交易所会员、智能路由和竞争场所。NPC 为保持教学市场流动性拥有虚拟无限报价能力；现实机构受资本、库存、监管、风险和运营约束。')}</p>
        <p>{t(language, 'The one-second auction is a simplification for readable order and deterministic replay. Real equity venues normally run continuous trading during the session, with specialized opening and closing auctions and venue-specific order handling. Real market data can be delayed, consolidated, fragmented, and affected by latency.', '一秒一轮撮合是为了提供清晰顺序和确定性回放的简化。现实股票场所通常在交易时段连续交易，并采用专门开盘/收盘集合竞价和场所特定订单处理。真实行情可能延迟、汇总、碎片化，并受网络时延影响。')}</p>
        <p>{t(language, 'FinPub events move a simulated fair-value input and let agents react; they never force the last price to jump. Real news reaches investors unevenly, interpretation varies, trading can pause, and price formation includes many venues and participants. The game illustrates a mechanism, never a real-event return forecast.', 'FinPub 事件会改变模拟公允价值输入，再由交易者作出反应；它不会强制让最新成交价跳变。现实新闻到达投资者的时间不一致，解读不同，交易可能暂停；价格形成涉及众多场所与参与者。游戏展示的是一种机制，而非现实事件收益预测。')}</p>
      </Section>
      <Section title={t(language, 'Margin financing, securities lending, and short selling', '融资融券、证券借贷与卖空')}>
        <p>{t(language, 'FinPub is a cash-only, long-only game. It does not support margin financing, securities lending, short selling, leverage, maintenance-margin calculations, margin calls, forced liquidation, stock-borrow availability, financing interest, borrow fees, dividend compensation, or collateral haircuts. A player must have enough available cash before buying and enough available inventory before selling. NPC virtual inventory exists only to maintain the teaching market’s liquidity and is not a player borrowing facility.', 'FinPub 是现金制、仅做多的游戏。它不支持融资买入、证券借贷、融券卖出、杠杆、维持保证金计算、追保、强制平仓、可借券库存、融资利息、借券费用、股息补偿或担保品折算。玩家买入前必须拥有足额可用现金，卖出前必须拥有足额可用持仓。NPC 的虚拟库存仅用于维持教学市场的流动性，不是供玩家借券的功能。')}</p>
        <p>{t(language, 'In A-share margin trading, an eligible investor provides collateral to an eligible securities firm, then borrows funds to buy eligible securities or borrows eligible securities to sell. This is not the same as an ordinary cash purchase. Eligibility, collateral ratios, concentration limits, interest, fees, available securities, contract terms, and forced-close-out arrangements are governed by current rules and broker agreements. A security may be tradable in cash but unavailable for financing or securities lending.', '在 A 股融资融券交易中，符合条件的投资者向具备资格的证券公司提供担保物，再借入资金买入可融资证券，或借入可融券证券后卖出。这不同于普通现金买入。适当性、担保物比例、集中度限制、利息、费用、可借证券、合同条款和强制平仓安排均受现行规则与券商协议约束。一只证券可以进行现金交易，却不一定可融资或可融券。')}</p>
        <p>{t(language, 'In U.S. markets, a margin account lets a broker-dealer lend cash against account collateral. It can increase purchasing power and losses; the broker may require additional collateral and may liquidate securities under the account agreement. A short sale normally requires borrowed stock or a documented reasonable basis to believe it can be borrowed before the sale is effected; stock-loan cost and availability can change. Execution, settlement, financing, borrow, and risk controls are distinct layers that FinPub intentionally does not model.', '在美国市场，保证金账户允许券商自营商以账户担保物为基础出借资金。它会同时放大购买力与损失；券商可能要求追加担保物，并可按照账户协议处置证券。卖空通常要求在卖出前已借入证券，或有经记录的合理依据相信能够借到证券；借券成本和可借性都会变化。成交、结算、融资、借券和风控是不同层面，FinPub 有意不进行建模。')}</p>
      </Section>
      <Section title={t(language, 'A-share market: what to keep in mind', 'A 股市场：需要理解的真实情况')}>
        <p>{t(language, 'China’s mainland equity market is organized around exchange rulebooks, broker access, registration and clearing arrangements, investor suitability requirements, and board-specific rules. The Shanghai and Shenzhen exchanges publish detailed trading rules; requirements differ across boards and instruments. FinPub is not a replica of any SSE or SZSE board.', '中国内地股票市场由交易所规则、券商接入、登记结算安排、投资者适当性要求和板块特定规则共同构成。上交所和深交所公布详细交易规则，不同板块和品种的要求也不同。FinPub 不应被理解为上交所或深交所任一板块的复制品。')}</p>
        <p>{t(language, 'For ordinary A-share cash equity trading, the familiar T+1 convention means shares bought today generally cannot be resold until the next trading day. This differs from FinPub, where a filled position can become available through the game’s reservation logic. Price limits, order types, lot sizes, and auction arrangements are board- and instrument-specific and are not fully represented here.', '对普通 A 股现货股票交易，常见的 T+1 交易惯例意味着当日买入的股票通常要到下一个交易日才能卖出。这与 FinPub 不同：在游戏中，成交后的持仓会依据订单冻结逻辑变为可用。涨跌幅限制、订单类型、申报数量和集合竞价安排也会因板块和品种不同而变化，游戏并未完整模拟。')}</p>
        <p>{t(language, 'Real A-share participants include retail investors, public and private funds, insurers, brokers, proprietary desks, and quantitative funds. In certain products or boards, liquidity providers and market makers operate under defined programs. Their orders are constrained by cash, inventory, compliance, risk limits, client mandates, and exchange rules. FinPub’s generic market-maker NPC is an educational abstraction, not a claim that every A-share stock has a U.S.-style designated market maker.', '真实 A 股参与者包括个人投资者、公私募基金、保险资金、券商、自营盘和量化基金；在特定产品或板块中，也有按特定制度运行的流动性提供者和做市商。他们的委托受现金、库存、合规、风控、客户授权和交易所规则约束。游戏中的通用做市 NPC 是教学抽象，并不意味着每只 A 股都有美股式指定做市商。')}</p>
      </Section>
      <Section title={t(language, 'U.S. equities: NYSE and Nasdaq', '美股：NYSE 与 Nasdaq')}>
        <p>{t(language, 'U.S. equities trade in a national market system with multiple exchanges, broker-dealers, market makers, alternative trading systems, and data feeds. NYSE and Nasdaq are both major listing and trading venues, but their market models and products are not identical. A broker may route an order according to its execution obligations and available markets; a visible quote on one venue is not necessarily the whole market.', '美国股票处于全国市场系统之中，涉及多个交易所、券商自营商、做市商、另类交易系统和行情数据源。NYSE 与 Nasdaq 都是重要的上市和交易场所，但其市场模型和产品并不完全相同。券商会依照其执行义务和可用市场路由订单；单一场所的一条可见报价不一定代表整个市场。')}</p>
        <p>{t(language, 'NYSE uses opening and closing auctions and has designated market makers for assigned securities. Nasdaq is an electronic market with registered market makers and its own opening and closing cross processes. Actual order handling depends on venue rules, order instructions, market conditions, and broker routing. FinPub’s single-book, single-venue view is useful for learning but omits fragmentation and routing.', 'NYSE 使用开盘、收盘集合竞价，并为指定证券设置指定做市商。Nasdaq 是电子化市场，拥有注册做市商及其开盘、收盘交叉撮合机制。真实订单处理取决于场所规则、订单指令、市场状态和券商路由。FinPub 的单订单簿、单场所视图适合学习，但忽略了市场碎片化和路由。')}</p>
        <p>{t(language, 'Most U.S. broker-dealer transactions in covered securities settle on a T+1 standard cycle. Settlement is different from execution: a trade can execute today while transfer and payment complete through the settlement system on the standard settlement date. FinPub combines these operating layers into an immediate in-game cash-and-position ledger.', '大多数美国券商自营商涉及的适用证券交易采用 T+1 标准结算周期。结算不同于即时成交：交易可以在今天执行，而证券交收和资金交割在标准结算日通过结算系统完成。FinPub 将这些运营层面合并成即时的游戏内现金和持仓账本。')}</p>
      </Section>
      <Section title={t(language, 'Who trades, and why', '谁在交易，以及为什么交易')}>
        <Term title={t(language, 'Market makers and liquidity providers', '做市商与流动性提供者')}><p>{t(language, 'A real market maker usually posts two-sided quotes, manages inventory, adjusts spreads for risk and volatility, and hedges or trades across venues. Some venues give formal roles and obligations; elsewhere firms simply supply liquidity actively. They do not have limitless capital and may widen or withdraw quotes under stress. FinPub’s market-maker NPC quotes around a simulated subjective value and inventory target to demonstrate these incentives.', '现实做市商通常双边报价、管理库存、依据风险与波动率调整价差，并进行对冲或跨场所交易。某些场所赋予正式角色和义务，另一些场所则有活跃的流动性提供者。他们没有无限资本，也可能在压力情形下扩大价差或撤出报价。FinPub 的做市 NPC 围绕模拟主观估值和库存目标报价，用于说明这些激励。')}</p></Term>
        <Term title={t(language, 'Value investors and fundamental funds', '价值投资者与基本面基金')}><p>{t(language, 'Value-oriented traders estimate earnings, cash flows, balance-sheet strength, discount rates, sector conditions, and comparable valuations. They may trade when an estimate differs from market price, while also managing position size, liquidity, timing, and risk. FinPub’s value NPC compresses this broad process into a subjective fair-value comparison.', '价值导向交易者会估计盈利、现金流、资产负债表质量、贴现率、行业环境和可比估值。当估计与市场价格存在差异时可能交易，同时还会管理仓位规模、流动性、时机和风险。FinPub 的价值 NPC 将这一宽泛过程压缩为主观公允价值比较。')}</p></Term>
        <Term title={t(language, 'Trend, quantitative, and execution traders', '趋势、量化与执行交易者')}><p>{t(language, 'Trend strategies react to price and volume patterns; quantitative strategies may use statistical signals, optimization, and risk models; execution algorithms focus on completing a parent order while controlling cost and information leakage. None is guaranteed to profit. FinPub’s trend NPC uses a deliberately small recent-price signal, not a production-grade quantitative model.', '趋势策略根据价格和成交量模式反应；量化策略可能使用统计信号、优化和风险模型；执行算法关注在控制成本和信息泄露的前提下完成母单。它们都不保证盈利。FinPub 的趋势 NPC 使用刻意简化的近期价格信号，并非生产级量化模型。')}</p></Term>
        <Term title={t(language, 'News-driven and retail traders', '新闻驱动与个人投资者')}><p>{t(language, 'News-driven traders assess whether information is new, material, credible, already priced, and relevant to an issuer or sector. Retail investors may trade for savings, diversification, personal views, hedging, or speculation. FinPub’s news NPC only weights a current simulated shock; it does not read real news. Its noise NPC is a model label for demand not fully explained by valuation, never a judgment about real people.', '新闻驱动交易者会判断信息是否新颖、重大、可信、是否已被定价，以及是否与公司或行业相关。个人投资者可能出于储蓄、分散配置、个人观点、对冲或投机而交易。FinPub 的新闻 NPC 只会对当前模拟冲击加权，不会阅读真实新闻。噪声 NPC 是描述无法完全由估值解释的需求的模型标签，并非对现实个人的评价。')}</p></Term>
      </Section>
      <Section title={t(language, 'Official reading and rule sources', '官方资料与规则来源')}>
        <p>{t(language, 'Rules change. For a real order, account, or market-access decision, read the current rulebook and ask your broker or a qualified professional. These links are starting points, not legal or trading advice.', '规则会变化。若涉及真实委托、账户或市场准入决策，请阅读现行规则并咨询券商或合格专业人士。以下链接只是起点，不构成法律或交易建议。')}</p>
        <ul className="wiki-links"><li><Source href="https://english.sse.com.cn/start/trading/mechanism/">{t(language, 'Shanghai Stock Exchange: trading mechanism', '上海证券交易所：交易机制')}</Source></li><li><Source href="https://www.sse.com.cn/services/tradingservice/margin/home/">{t(language, 'Shanghai Stock Exchange: margin financing and securities lending', '上海证券交易所：融资融券')}</Source></li><li><Source href="https://www.szse.cn/English/">{t(language, 'Shenzhen Stock Exchange: official site and rule materials', '深圳证券交易所：官网与规则资料')}</Source></li><li><Source href="https://www.sec.gov/divisions/marketreg/t1settlement">{t(language, 'U.S. SEC: T+1 settlement', '美国 SEC：T+1 结算')}</Source></li><li><Source href="https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins-29">{t(language, 'U.S. SEC investor education: margin accounts', '美国 SEC 投资者教育：保证金账户')}</Source></li><li><Source href="https://www.investor.gov/introduction-investing/investing-basics/how-stock-markets-work/stock-purchases-and-sales-long-and">{t(language, 'U.S. SEC investor education: long and short sales', '美国 SEC 投资者教育：多头与卖空')}</Source></li><li><Source href="https://www.nyse.com/markets/nyse/trading-model">{t(language, 'NYSE: trading model and designated market makers', 'NYSE：交易模型与指定做市商')}</Source></li><li><Source href="https://www.nasdaqtrader.com/Trader.aspx?id=MarketMaker">{t(language, 'Nasdaq Trader: market maker program', 'Nasdaq Trader：做市商计划')}</Source></li><li><Source href="https://www.sec.gov/rules-regulations/major-rules/market-structure">{t(language, 'U.S. SEC: market structure and Regulation NMS', '美国 SEC：市场结构与 Regulation NMS')}</Source></li></ul>
      </Section>
    </article>
    <footer className="wiki-footer">{zh ? 'FinPub Wiki · 真实规则以交易所、监管机构和券商的现行文件为准。' : 'FinPub Wiki · For real markets, current exchange, regulator, and broker materials control.'}</footer>
  </main>;
}
